// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf_0Bu05J7g3kajpn5qo2ZJkR-hke0BOg',
    appId: '1:140792705515:web:4d4c31600bcdd7526ee9ae',
    messagingSenderId: '140792705515',
    projectId: 'pizza-planet-app-03082904',
    authDomain: 'pizza-planet-app-03082904.firebaseapp.com',
    databaseURL: 'https://pizza-planet-app-03082904-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pizza-planet-app-03082904.appspot.com',
    measurementId: 'G-4J7WVDW0Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNiP-_V8SpEviAuJruq8vEjZEucwP82lA',
    appId: '1:140792705515:android:c8a956d7c20b767a6ee9ae',
    messagingSenderId: '140792705515',
    projectId: 'pizza-planet-app-03082904',
    databaseURL: 'https://pizza-planet-app-03082904-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pizza-planet-app-03082904.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkvW5-vJ1q5Iyi9CU6Mt4EUdGOFrfxqok',
    appId: '1:140792705515:ios:e9a75b1a5f27e8876ee9ae',
    messagingSenderId: '140792705515',
    projectId: 'pizza-planet-app-03082904',
    databaseURL: 'https://pizza-planet-app-03082904-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pizza-planet-app-03082904.appspot.com',
    androidClientId: '140792705515-0m75c03154v3qf2qh5cp8kho7ftbdvot.apps.googleusercontent.com',
    iosClientId: '140792705515-pcmnd1f6aqh8t3f1eefotfbqc1immer3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaPlanet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkvW5-vJ1q5Iyi9CU6Mt4EUdGOFrfxqok',
    appId: '1:140792705515:ios:e9a75b1a5f27e8876ee9ae',
    messagingSenderId: '140792705515',
    projectId: 'pizza-planet-app-03082904',
    databaseURL: 'https://pizza-planet-app-03082904-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pizza-planet-app-03082904.appspot.com',
    androidClientId: '140792705515-0m75c03154v3qf2qh5cp8kho7ftbdvot.apps.googleusercontent.com',
    iosClientId: '140792705515-pcmnd1f6aqh8t3f1eefotfbqc1immer3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaPlanet',
  );
}
